version: "3"
services:
  pgwatch2:
    image: nexus.eltex.loc:9007/eccm/pgwatch2:test
    build:
      context: .
      dockerfile: ./docker/Dockerfile-postgres-only
    environment:
      PW2_VERBOSE: INFO
      PW2_ADHOC_CONN_STR: "postgresql://pgwatch2:pgwatch2admin@100.110.2.6:${POSTGRES_PORT:-5432}/${ECCM_POSTGRES_DB:-eccm}"   # строка подключения к опрашиваемой БД,
      # PW2_ADHOC_CONFIG: '{"archiver":60,"backends":60,"bgwriter":60,"change_events":300,"db_stats":60,"db_size":300,"index_stats":900,"instance_up":60,"locks":60,"locks_mode":60,"replication":120,"replication_slots":120,"logical_subscriptions":120,"server_log_event_counts":60,"settings":7200,"sequence_health":3600,"sproc_stats":180,"stat_activity":30,"stat_statements":180,"stat_statements_calls":60,"table_bloat_approx_summary_sql":7200,"table_io_stats":600,"table_stats":300,"wal":60,"wal_size":120,"kpi":120,"stat_ssl":120,"wal_receiver":120}'
      PW2_ADHOC_CONFIG: '{"kpi":60,"eccm_total_devices":300}'
      PW2_ADHOC_CREATE_HELPERS: 'true'   # Try to auto-create helpers. Needs superuser to succeed.      
      PW2_ADHOC_NAME: ${ECCM_POSTGRES_DB:-eccm}   # Unique 'dbname'. Default: adhoc
    ports:
      - "5432:5432"
      - "9187:9187"
      - "8081:8081"
